### ISSUE TITLE
TE-127: Hot Text Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#127]
![img_20170412_131234](https://cloud.githubusercontent.com/assets/8982139/24957998/0d8e73f0-1f8e-11e7-8e5d-6bd1b8a13b40.jpg)
![img_20170412_131328](https://cloud.githubusercontent.com/assets/8982139/24958036/2e93a548-1f8e-11e7-88b2-2e75b85cdde0.jpg)
![img_20170412_143909](https://cloud.githubusercontent.com/assets/8982139/24959001/9375c506-1f91-11e7-9df6-965fb076bbeb.jpg)

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [x] when saving the model answers of hot textQuestion without select answers we get this error

![hottexterror](https://user-images.githubusercontent.com/12035045/27771568-68e62696-5f51-11e7-885f-62ac531dd748.png)

- [x] when saving the updates of deactivate model answer of hot text question we get this error

![selectpoint](https://user-images.githubusercontent.com/12035045/27770913-79f8696c-5f47-11e7-9056-1fed8f21f814.png)

**Comment by AbdElmoneimMohamed** [comment]
## QA issues
@badr4php 

- [x] the error message display when create hotText question without model answers must be change
we can use " This question must has at least one model answer with right answer" instead of  "This question should only has one model answer with right answer !
"
![hottexterror1](https://user-images.githubusercontent.com/12035045/28525760-992b5fde-7085-11e7-96d1-8ba04748a329.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/104
